channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=3.0.16
- jupyter-offlinenotebook=0.2.1
- nodejs=12
- nbconvert=6.1
# Python Kernel
- ipykernel=6.0.1
- xeus-python=0.12.5
- ipywidgets=7.6.3
- widgetsnbextension=3.5.1
- ipyleaflet=0.14
- altair=4.1
- bqplot=0.12.29
- dask=2021.7
- matplotlib=3.4.2
- pandas=1.3
- python=3.9.6
- scikit-image=0.18.2
- scikit-learn=0.24.2
- seaborn=0.11.1
- tensorflow=2.5
- sympy=1.8
- pyyaml=5.4.1
- traittypes==0.2.1
- invoke=1.6
